# Generated by Django 4.2.7 on 2024-03-16 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_breg_id_alter_drreg_id_alter_labpay_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('10.00 AM - 10.10 AM', '10.00 AM - 10.10 AM'), ('10.10 AM - 10.20 AM', '10.10 AM - 10.20 AM'), ('10.20 AM - 10.30 AM', '10.20 AM - 10.30 AM'), ('10.30 AM - 10.40 AM', '10.30 AM - 10.40 AM'), ('10.40 AM - 10.50 AM', '10.40 AM - 10.50 AM'), ('10.50 AM - 11.00 AM', '10.50 AM - 11.00 AM'), ('11.00 AM - 11.10 AM', '11.00 AM - 11.10 AM'), ('11.10 AM - 11.20 AM', '11.10 AM - 11.20 AM'), ('11.20 AM - 11.30 AM', '11.20 AM - 11.30 AM'), ('11.30 AM - 11.40 AM', '11.30 AM - 11.40 AM'), ('11.40 AM - 11.50 AM', '11.40 AM - 11.50 AM'), ('11.50 AM - 12.00 AM', '12.50 AM - 12.00 AM'), ('12.00 AM - 12.10 AM', '12.00 AM - 12.10 AM'), ('12.10 AM - 12.20 AM', '12.10 AM - 12.20 AM'), ('12.20 AM - 11.30 AM', '12.20 AM - 12.30 AM')], max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.drreg')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.reg')),
            ],
        ),
    ]
