# Generated by Django 4.2.7 on 2024-03-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0031_alter_bookdoctor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdoctor',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
