# Generated by Django 4.2.7 on 2024-03-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_alter_bookdoctor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdoctor',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
