# Generated by Django 5.0.1 on 2024-03-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_bookdoctor_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdoctor',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
