# Generated by Django 5.0.1 on 2024-03-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_bookdoctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
