# Generated by Django 5.0.1 on 2024-03-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_pay_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='time',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
