# Generated by Django 5.0.1 on 2024-03-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_pay_date_pay_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='demail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
