# Generated by Django 5.0.1 on 2024-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0037_pay_demail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
