# Generated by Django 5.0.1 on 2024-03-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0039_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
